let data = [
  {
    audience: 'STM',
    value: 30,
    categories: [
      {
        category: 'Arts & Entertainment',
        audience: 'STM',
        value: 20,
        metakws: [
          {
            keyword: 'cnn',
            value: 10,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'cnnpolitics',
            value: 4,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'politics',
            value: 3,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'entertainment',
            value: 3,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'nfl',
            value: 2,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'sport',
            value: 2,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'health',
            value: 2,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'game',
            value: 2,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'video',
            value: 2,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'world',
            value: 2,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
        ],
        keyphrases: [
          {
            keyphrase: 'grocery games',
            value: 10,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'star',
            value: 8,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'international arabic',
            value: 7,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'arabic español',
            value: 7,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'photo',
            value: 7,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'biden presidency',
            value: 6,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'presidency facts',
            value: 6,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'latest',
            value: 6,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'november',
            value: 6,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'big',
            value: 6,
            audience: 'STM',
            category: 'Arts & Entertainment',
          },
        ],
      },
      {
        category: 'Sports',
        audience: 'STM',
        value: 20,
        metakws: [
          { keyword: 'nfl', value: 3, audience: 'STM', category: 'Sports' },
          {
            keyword: 'football',
            value: 2,
            audience: 'STM',
            category: 'Sports',
          },
          { keyword: 'sport', value: 2, audience: 'STM', category: 'Sports' },
          { keyword: 'car', value: 1, audience: 'STM', category: 'Sports' },
          {
            keyword: 'jalopnik',
            value: 1,
            audience: 'STM',
            category: 'Sports',
          },
          { keyword: 'soccer', value: 1, audience: 'STM', category: 'Sports' },
          { keyword: 'cnn', value: 1, audience: 'STM', category: 'Sports' },
          { keyword: 'nba', value: 1, audience: 'STM', category: 'Sports' },
          { keyword: 'video', value: 1, audience: 'STM', category: 'Sports' },
          {
            keyword: 'college football',
            value: 1,
            audience: 'STM',
            category: 'Sports',
          },
        ],
        keyphrases: [
          { keyphrase: 'star', value: 2, audience: 'STM', category: 'Sports' },
          { keyphrase: 'big', value: 2, audience: 'STM', category: 'Sports' },
          { keyphrase: 'skip', value: 2, audience: 'STM', category: 'Sports' },
          {
            keyphrase: 'head coach',
            value: 2,
            audience: 'STM',
            category: 'Sports',
          },
          { keyphrase: 'photo', value: 1, audience: 'STM', category: 'Sports' },
          {
            keyphrase: 'high school',
            value: 1,
            audience: 'STM',
            category: 'Sports',
          },
          { keyphrase: 'team', value: 1, audience: 'STM', category: 'Sports' },
          {
            keyphrase: 'report',
            value: 1,
            audience: 'STM',
            category: 'Sports',
          },
          { keyphrase: 'run', value: 1, audience: 'STM', category: 'Sports' },
          {
            keyphrase: 'ad free',
            value: 1,
            audience: 'STM',
            category: 'Sports',
          },
        ],
      },
      {
        category: 'Technology & Computing',
        audience: 'STM',
        value: 20,
        metakws: [
          {
            keyword: 'business',
            value: 2,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyword: 'general news',
            value: 2,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyword: 'sport',
            value: 2,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyword: 'nfl',
            value: 2,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyword: 'donald trump',
            value: 1,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyword: 'united states',
            value: 1,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyword: 'health',
            value: 1,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyword: 'entertainment',
            value: 1,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyword: 'covid',
            value: 1,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyword: 'shooting',
            value: 1,
            audience: 'STM',
            category: 'Technology & Computing',
          },
        ],
        keyphrases: [
          {
            keyphrase: 'paid program',
            value: 8,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'say',
            value: 5,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'brandvoice paid',
            value: 5,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'november',
            value: 5,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'ad free',
            value: 4,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'big',
            value: 4,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'photo',
            value: 4,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'recipe',
            value: 3,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'world',
            value: 3,
            audience: 'STM',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'told',
            value: 3,
            audience: 'STM',
            category: 'Technology & Computing',
          },
        ],
      },
    ],
  },
  {
    audience: 'Conversion Ready',
    value: 30,
    categories: [
      {
        category: 'Arts & Entertainment',
        audience: 'Conversion Ready',
        value: 20,
        metakws: [
          {
            keyword: 'cnn',
            value: 10,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'politics',
            value: 4,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'cnnpolitics',
            value: 3,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'dailymail news',
            value: 3,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'joe biden',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'sport',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'donald trump',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'entertainment',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'nfl',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'health',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
        ],
        keyphrases: [
          {
            keyphrase: 'high school',
            value: 9,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'grocery games',
            value: 9,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'primary sidebar',
            value: 8,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'including',
            value: 6,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'little',
            value: 6,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'great',
            value: 5,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'san francisco',
            value: 5,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'latest',
            value: 5,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'work',
            value: 5,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'vaccine mandate',
            value: 5,
            audience: 'Conversion Ready',
            category: 'Arts & Entertainment',
          },
        ],
      },
      {
        category: 'Sports',
        audience: 'Conversion Ready',
        value: 20,
        metakws: [
          {
            keyword: 'cnn',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyword: 'nfl',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyword: 'logos logo',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyword: 'football',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyword: 'college football',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyword: 'united states',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyword: 'minor league',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyword: 'los angeles',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyword: 'sport',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyword: 'jalopnik',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
        ],
        keyphrases: [
          {
            keyphrase: 'high school',
            value: 4,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyphrase: 'head coach',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyphrase: 'champions league',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyphrase: 'los angeles',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyphrase: 'pf pts',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyphrase: 'skip',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyphrase: 'big',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyphrase: 'star',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyphrase: 'misses foot',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
          {
            keyphrase: 'player',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Sports',
          },
        ],
      },
      {
        category: 'Technology & Computing',
        audience: 'Conversion Ready',
        value: 20,
        metakws: [
          {
            keyword: 'joe biden',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyword: 'sport',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyword: 'football',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyword: 'general news',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyword: 'donald trump',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyword: 'united states',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyword: 'cnn',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyword: 'nfl',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyword: 'entertainment',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyword: 'gizmodo',
            value: 1,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
        ],
        keyphrases: [
          {
            keyphrase: 'paid program',
            value: 10,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'brandvoice paid',
            value: 6,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'latest',
            value: 3,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'say',
            value: 3,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'big',
            value: 3,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'including',
            value: 3,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'primary sidebar',
            value: 3,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'high school',
            value: 3,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'november',
            value: 3,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'great',
            value: 2,
            audience: 'Conversion Ready',
            category: 'Technology & Computing',
          },
        ],
      },
    ],
  },
  {
    audience: 'Fan Development',
    value: 30,
    categories: [
      {
        category: 'Arts & Entertainment',
        audience: 'Fan Development',
        value: 20,
        metakws: [
          {
            keyword: 'cnn',
            value: 10,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'joe biden',
            value: 5,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'dailymail news',
            value: 5,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'news new',
            value: 5,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'donald trump',
            value: 4,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'politic',
            value: 4,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'cnnpolitics',
            value: 3,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'entertainment',
            value: 3,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'music new',
            value: 2,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyword: 'dailymail tvshowbiz',
            value: 2,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
        ],

        keyphrases: [
          {
            keyphrase: 'primary sidebar',
            value: 10,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'high school',
            value: 8,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'sidebar skip',
            value: 7,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'skip skip',
            value: 7,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'parent influence',
            value: 7,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'secondary skip',
            value: 6,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'images photo',
            value: 6,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'use contribute',
            value: 6,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'published december',
            value: 5,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
          {
            keyphrase: 'jennifer lopez',
            value: 5,
            audience: 'Fan Development',
            category: 'Arts & Entertainment',
          },
        ],
      },
      {
        category: 'Sports',
        audience: 'Fan Development',
        value: 20,
        metakws: [
          {
            keyword: 'picks prediction',
            value: 3,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyword: 'college football',
            value: 3,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyword: 'cnn',
            value: 2,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyword: 'sport',
            value: 2,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyword: 'nfl',
            value: 2,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyword: 'los angeles',
            value: 2,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyword: 'nba',
            value: 2,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyword: 'dailymail news',
            value: 1,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyword: 'green bay',
            value: 1,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyword: 'notre dame',
            value: 1,
            audience: 'Fan Development',
            category: 'Sports',
          },
        ],
        keyphrases: [
          {
            keyphrase: 'high school',
            value: 3,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyphrase: 'head coach',
            value: 2,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyphrase: 'big',
            value: 2,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyphrase: 'primary sidebar',
            value: 2,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyphrase: 'los angeles',
            value: 2,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyphrase: 'parent influence',
            value: 1,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyphrase: 'belt joined',
            value: 1,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyphrase: 'misses foot',
            value: 1,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyphrase: 'san francisco',
            value: 1,
            audience: 'Fan Development',
            category: 'Sports',
          },
          {
            keyphrase: 'skip skip',
            value: 1,
            audience: 'Fan Development',
            category: 'Sports',
          },
        ],
      },
      {
        category: 'Technology & Computing',
        audience: 'Fan Development',
        value: 20,
        metakws: [
          {
            keyword: 'joe biden',
            value: 4,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyword: 'donald trump',
            value: 3,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyword: 'cnn',
            value: 2,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyword: 'general news',
            value: 2,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyword: 'sport',
            value: 2,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyword: 'county',
            value: 2,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyword: 'police',
            value: 2,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyword: 'united states',
            value: 1,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyword: 'new york',
            value: 1,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyword: 'entertainment',
            value: 1,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
        ],
        keyphrases: [
          {
            keyphrase: 'primary sidebar',
            value: 7,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'skip skip',
            value: 4,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'sidebar skip',
            value: 4,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'secondary skip',
            value: 4,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'high school',
            value: 4,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'paid program',
            value: 3,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'ghislaine maxwell',
            value: 3,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'faith hill',
            value: 2,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'big',
            value: 2,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
          {
            keyphrase: 'work',
            value: 2,
            audience: 'Fan Development',
            category: 'Technology & Computing',
          },
        ],
      },
    ],
  },
];

export default data;
