let data = [
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'cnn',
    count: 1093,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 10,
  },
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'politics',
    count: 425,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 4,
  },
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'cnnpolitics',
    count: 380,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'dailymail news',
    count: 313,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'joe biden',
    count: 267,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'sport',
    count: 249,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'donald trump',
    count: 245,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'entertainment',
    count: 239,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'nfl',
    count: 236,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Arts & Entertainment',
    keyword: 'health',
    count: 190,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'cnn',
    count: 264,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'nfl',
    count: 212,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'logos logo',
    count: 187,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'football',
    count: 182,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'college football',
    count: 177,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'united states',
    count: 160,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'minor league',
    count: 157,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'los angeles',
    count: 154,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'sport',
    count: 149,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Sports',
    keyword: 'jalopnik',
    count: 145,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'joe biden',
    count: 191,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'sport',
    count: 161,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'football',
    count: 161,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'general news',
    count: 160,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'donald trump',
    count: 160,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'united states',
    count: 159,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'cnn',
    count: 157,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'nfl',
    count: 143,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'entertainment',
    count: 143,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Conversion Ready',
    category: 'Technology & Computing',
    keyword: 'gizmodo',
    count: 131,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'cnn',
    count: 474,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 10,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'cnnpolitics',
    count: 194,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 4,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'politics',
    count: 147,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'entertainment',
    count: 111,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'nfl',
    count: 103,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'sport',
    count: 100,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'health',
    count: 94,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'game',
    count: 90,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'video',
    count: 83,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Arts & Entertainment',
    keyword: 'world',
    count: 82,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'nfl',
    count: 134,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'football',
    count: 76,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'sport',
    count: 70,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'car',
    count: 49,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'jalopnik',
    count: 48,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'soccer',
    count: 43,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'cnn',
    count: 41,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'nba',
    count: 40,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'video',
    count: 38,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Sports',
    keyword: 'college football',
    count: 36,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'business',
    count: 82,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'general news',
    count: 80,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'sport',
    count: 79,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'nfl',
    count: 74,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'donald trump',
    count: 56,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'united states',
    count: 56,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'health',
    count: 54,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'entertainment',
    count: 53,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'covid',
    count: 53,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'STM',
    category: 'Technology & Computing',
    keyword: 'shooting',
    count: 45,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'cnn',
    count: 1214,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 10,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'joe biden',
    count: 664,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 5,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'dailymail news',
    count: 605,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 5,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'news new',
    count: 601,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 5,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'donald trump',
    count: 575,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 4,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'politic',
    count: 512,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 4,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'cnnpolitics',
    count: 389,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'entertainment',
    count: 382,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'music new',
    count: 348,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Arts & Entertainment',
    keyword: 'dailymail tvshowbiz',
    count: 346,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'picks prediction',
    count: 416,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'college football',
    count: 389,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'cnn',
    count: 289,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'sport',
    count: 288,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'nfl',
    count: 286,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'los angeles',
    count: 283,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'nba',
    count: 260,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'dailymail news',
    count: 216,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'green bay',
    count: 187,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Fan Development',
    category: 'Sports',
    keyword: 'notre dame',
    count: 181,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'joe biden',
    count: 510,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 4,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'donald trump',
    count: 403,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 3,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'cnn',
    count: 298,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'general news',
    count: 293,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'sport',
    count: 265,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'county',
    count: 248,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'police',
    count: 240,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 2,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'united states',
    count: 237,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'new york',
    count: 237,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
  {
    audience: 'Fan Development',
    category: 'Technology & Computing',
    keyword: 'entertainment',
    count: 225,
    audience_radius: 30,
    category_radius: 20,
    keyword_radius: 1,
  },
];

module.exports = data;
