let data = [
  ['Conversion Ready', 'Arts & Entertainment', 'cnn', 1093, 10],
  ['Conversion Ready', 'Arts & Entertainment', 'politics', 425, 4],
  ['Conversion Ready', 'Arts & Entertainment', 'cnnpolitics', 380, 3],
  ['Conversion Ready', 'Arts & Entertainment', 'dailymail news', 313, 3],
  ['Conversion Ready', 'Arts & Entertainment', 'joe biden', 267, 2],
  ['Conversion Ready', 'Arts & Entertainment', 'sport', 249, 2],
  ['Conversion Ready', 'Arts & Entertainment', 'donald trump', 245, 2],
  ['Conversion Ready', 'Arts & Entertainment', 'entertainment', 239, 2],
  ['Conversion Ready', 'Arts & Entertainment', 'nfl', 236, 2],
  ['Conversion Ready', 'Arts & Entertainment', 'health', 190, 2],
  ['Conversion Ready', 'Sports', 'cnn', 264, 2],
  ['Conversion Ready', 'Sports', 'nfl', 212, 2],
  ['Conversion Ready', 'Sports', 'logos logo', 187, 2],
  ['Conversion Ready', 'Sports', 'football', 182, 1],
  ['Conversion Ready', 'Sports', 'college football', 177, 1],
  ['Conversion Ready', 'Sports', 'united states', 160, 1],
  ['Conversion Ready', 'Sports', 'minor league', 157, 1],
  ['Conversion Ready', 'Sports', 'los angeles', 154, 1],
  ['Conversion Ready', 'Sports', 'sport', 149, 1],
  ['Conversion Ready', 'Sports', 'jalopnik', 145, 1],
  ['Conversion Ready', 'Technology & Computing', 'joe biden', 191, 2],
  ['Conversion Ready', 'Technology & Computing', 'sport', 161, 1],
  ['Conversion Ready', 'Technology & Computing', 'football', 161, 1],
  ['Conversion Ready', 'Technology & Computing', 'general news', 160, 1],
  ['Conversion Ready', 'Technology & Computing', 'donald trump', 160, 1],
  ['Conversion Ready', 'Technology & Computing', 'united states', 159, 1],
  ['Conversion Ready', 'Technology & Computing', 'cnn', 157, 1],
  ['Conversion Ready', 'Technology & Computing', 'nfl', 143, 1],
  ['Conversion Ready', 'Technology & Computing', 'entertainment', 143, 1],
  ['Conversion Ready', 'Technology & Computing', 'gizmodo', 131, 1],
  ['STM', 'Arts & Entertainment', 'cnn', 474, 10],
  ['STM', 'Arts & Entertainment', 'cnnpolitics', 194, 4],
  ['STM', 'Arts & Entertainment', 'politics', 147, 3],
  ['STM', 'Arts & Entertainment', 'entertainment', 111, 3],
  ['STM', 'Arts & Entertainment', 'nfl', 103, 2],
  ['STM', 'Arts & Entertainment', 'sport', 100, 2],
  ['STM', 'Arts & Entertainment', 'health', 94, 2],
  ['STM', 'Arts & Entertainment', 'game', 90, 2],
  ['STM', 'Arts & Entertainment', 'video', 83, 2],
  ['STM', 'Arts & Entertainment', 'world', 82, 2],
  ['STM', 'Sports', 'nfl', 134, 3],
  ['STM', 'Sports', 'football', 76, 2],
  ['STM', 'Sports', 'sport', 70, 2],
  ['STM', 'Sports', 'car', 49, 1],
  ['STM', 'Sports', 'jalopnik', 48, 1],
  ['STM', 'Sports', 'soccer', 43, 1],
  ['STM', 'Sports', 'cnn', 41, 1],
  ['STM', 'Sports', 'nba', 40, 1],
  ['STM', 'Sports', 'video', 38, 1],
  ['STM', 'Sports', 'college football', 36, 1],
  ['STM', 'Technology & Computing', 'business', 82, 2],
  ['STM', 'Technology & Computing', 'general news', 80, 2],
  ['STM', 'Technology & Computing', 'sport', 79, 2],
  ['STM', 'Technology & Computing', 'nfl', 74, 2],
  ['STM', 'Technology & Computing', 'donald trump', 56, 1],
  ['STM', 'Technology & Computing', 'united states', 56, 1],
  ['STM', 'Technology & Computing', 'health', 54, 1],
  ['STM', 'Technology & Computing', 'entertainment', 53, 1],
  ['STM', 'Technology & Computing', 'covid', 53, 1],
  ['STM', 'Technology & Computing', 'shooting', 45, 1],
  ['Fan Development', 'Arts & Entertainment', 'cnn', 1214, 10],
  ['Fan Development', 'Arts & Entertainment', 'joe biden', 664, 5],
  ['Fan Development', 'Arts & Entertainment', 'dailymail news', 605, 5],
  ['Fan Development', 'Arts & Entertainment', 'news new', 601, 5],
  ['Fan Development', 'Arts & Entertainment', 'donald trump', 575, 4],
  ['Fan Development', 'Arts & Entertainment', 'politic', 512, 4],
  ['Fan Development', 'Arts & Entertainment', 'cnnpolitics', 389, 3],
  ['Fan Development', 'Arts & Entertainment', 'entertainment', 382, 3],
  ['Fan Development', 'Arts & Entertainment', 'music new', 348, 2],
  ['Fan Development', 'Arts & Entertainment', 'dailymail tvshowbiz', 346, 2],
  ['Fan Development', 'Sports', 'picks prediction', 416, 3],
  ['Fan Development', 'Sports', 'college football', 389, 3],
  ['Fan Development', 'Sports', 'cnn', 289, 2],
  ['Fan Development', 'Sports', 'sport', 288, 2],
  ['Fan Development', 'Sports', 'nfl', 286, 2],
  ['Fan Development', 'Sports', 'los angeles', 283, 2],
  ['Fan Development', 'Sports', 'nba', 260, 2],
  ['Fan Development', 'Sports', 'dailymail news', 216, 1],
  ['Fan Development', 'Sports', 'green bay', 187, 1],
  ['Fan Development', 'Sports', 'notre dame', 181, 1],
  ['Fan Development', 'Technology & Computing', 'joe biden', 510, 4],
  ['Fan Development', 'Technology & Computing', 'donald trump', 403, 3],
  ['Fan Development', 'Technology & Computing', 'cnn', 298, 2],
  ['Fan Development', 'Technology & Computing', 'general news', 293, 2],
  ['Fan Development', 'Technology & Computing', 'sport', 265, 2],
  ['Fan Development', 'Technology & Computing', 'county', 248, 2],
  ['Fan Development', 'Technology & Computing', 'police', 240, 2],
  ['Fan Development', 'Technology & Computing', 'united states', 237, 1],
  ['Fan Development', 'Technology & Computing', 'new york', 237, 1],
  ['Fan Development', 'Technology & Computing', 'entertainment', 225, 1],
];
